[config]
model = "openrouter/inclusionai/ling-3.0-flash-fin:free"
fallback_models = ["openrouter/inclusionai/ling-3.0-flash-fin:free"]

[github_action_config]
auto_review = true
auto_describe = true
auto_improve = true
enable_synchronize = true
handle_push_trigger = true

[openai]
model = "openrouter/inclusionai/ling-3.0-flash-fin:free"

[pr_reviewer]
require_security_review = true
